[theme]
base="light"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 500

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true

[ui]
hideTopBar = false
