[theme]
base="light"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 500
enableWebsocketCompression = false
allowRunOnSave = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[ui]
hideTopBar = false

[runner]
magicEnabled = false
